# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Auto_Poisson_Gibbs_Batch_Cpp <- function(Nsample, graph, thresholds, Winsorized, nIter) {
    .Call(`_CARlasso_Auto_Poisson_Gibbs_Batch_Cpp`, Nsample, graph, thresholds, Winsorized, nIter)
}

Auto_Poisson_Pseudo_likelihood_Cpp <- function(Sample, graph, thresholds) {
    .Call(`_CARlasso_Auto_Poisson_Pseudo_likelihood_Cpp`, Sample, graph, thresholds)
}

CAR_ALASSO_randeff_Cpp <- function(data, design, design_r, membership, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, alpha, beta, lambda_diag, progress) {
    .Call(`_CARlasso_CAR_ALASSO_randeff_Cpp`, data, design, design_r, membership, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, alpha, beta, lambda_diag, progress)
}

CAR_ALASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, lambda_diag, progress) {
    .Call(`_CARlasso_CAR_ALASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, lambda_diag, progress)
}

CAR_LASSO_randeff_Cpp <- function(data, design, design_r, membership, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, alpha, beta, progress) {
    .Call(`_CARlasso_CAR_LASSO_randeff_Cpp`, data, design, design_r, membership, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, alpha, beta, progress)
}

CAR_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress) {
    .Call(`_CARlasso_CAR_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress)
}

update_car_Omega_adp_helper <- function(Omega, data, design, mu, beta, lambda_curr, k, p, n) {
    invisible(.Call(`_CARlasso_update_car_Omega_adp_helper`, Omega, data, design, mu, beta, lambda_curr, k, p, n))
}

update_car_tau2_adp_helper <- function(beta, lambda2, Omega, k, p, n) {
    .Call(`_CARlasso_update_car_tau2_adp_helper`, beta, lambda2, Omega, k, p, n)
}

update_car_lambda_Omega_adp_helper <- function(lambda_curr, Omega, r, delta) {
    invisible(.Call(`_CARlasso_update_car_lambda_Omega_adp_helper`, lambda_curr, Omega, r, delta))
}

sec_dev_Omegasl_Omega <- function(design, Sigma, beta, mu, s, l) {
    .Call(`_CARlasso_sec_dev_Omegasl_Omega`, design, Sigma, beta, mu, s, l)
}

CAR_FI <- function(design, Omega, beta, mu, k, p) {
    .Call(`_CARlasso_CAR_FI`, design, Omega, beta, mu, k, p)
}

CAR_FI_graph <- function(design, Omega, beta, mu, k, p) {
    .Call(`_CARlasso_CAR_FI_graph`, design, Omega, beta, mu, k, p)
}

CAR_FI_beta <- function(design, Omega, beta, mu, k, p) {
    .Call(`_CARlasso_CAR_FI_beta`, design, Omega, beta, mu, k, p)
}

CAR_FI_para <- function(Design, Omega, beta, mu, k, p) {
    .Call(`_CARlasso_CAR_FI_para`, Design, Omega, beta, mu, k, p)
}

update_car_beta_helper <- function(data, design, mu, tau2, Omega, k, p, n) {
    .Call(`_CARlasso_update_car_beta_helper`, data, design, mu, tau2, Omega, k, p, n)
}

update_car_mu_helper <- function(data, design, beta, Omega, k, p, n) {
    .Call(`_CARlasso_update_car_mu_helper`, data, design, beta, Omega, k, p, n)
}

update_car_Omega_helper <- function(Omega, data, design, mu, beta, lambda_curr, k, p, n) {
    invisible(.Call(`_CARlasso_update_car_Omega_helper`, Omega, data, design, mu, beta, lambda_curr, k, p, n))
}

update_car_tau2_helper <- function(beta, lambda2, Omega, k, p, n) {
    .Call(`_CARlasso_update_car_tau2_helper`, beta, lambda2, Omega, k, p, n)
}

update_car_nu_helper <- function(data, design, design_r, membership, beta, mu, xi, Omega, k, pr, n) {
    .Call(`_CARlasso_update_car_nu_helper`, data, design, design_r, membership, beta, mu, xi, Omega, k, pr, n)
}

update_xi_helper <- function(xi, nu, membership, alpha, beta, k, pr, m) {
    invisible(.Call(`_CARlasso_update_xi_helper`, xi, nu, membership, alpha, beta, k, pr, m))
}

get_data_centered <- function(centered_data, data, design_r, nu, Omega) {
    invisible(.Call(`_CARlasso_get_data_centered`, centered_data, data, design_r, nu, Omega))
}

expected_G_eigen <- function(new_design, old_design, CAR_model, k, p, n_new, n_old, summary) {
    .Call(`_CARlasso_expected_G_eigen`, new_design, old_design, CAR_model, k, p, n_new, n_old, summary)
}

G_det <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_G_det`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

expected_G_det <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_expected_G_det`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

G_det_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_G_det_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

expected_G_det_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_expected_G_det_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

G_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_G_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

expected_G_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_expected_G_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

full_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_full_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

expected_all_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_expected_all_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

full_det_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_full_det_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

expected_full_det_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_expected_full_det_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

beta_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_beta_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

expected_beta_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_expected_beta_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

expected_invG_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_expected_invG_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

PIbeta_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_PIbeta_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

expected_PIbeta_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_expected_PIbeta_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

PIfull_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_PIfull_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

expected_PIfull_tr_para <- function(new_design, old_design, CAR_model, k, p, n_new, n_old) {
    .Call(`_CARlasso_expected_PIfull_tr_para`, new_design, old_design, CAR_model, k, p, n_new, n_old)
}

rgig <- function(lambda, chi, psi) {
    .Call(`_CARlasso_rgig`, lambda, chi, psi)
}

Ising_LASSO_Cpp <- function(data_, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_J, delta_J, propsd_mu, propsd_beta, propsd_J, propsd_lambda, exact, nauxIter, progress, verbos, reportby) {
    .Call(`_CARlasso_Ising_LASSO_Cpp`, data_, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_J, delta_J, propsd_mu, propsd_beta, propsd_J, propsd_lambda, exact, nauxIter, progress, verbos, reportby)
}

IsingSamplerCpp <- function(n, graph, thresholds, nIter, responses, exact) {
    .Call(`_CARlasso_IsingSamplerCpp`, n, graph, thresholds, nIter, responses, exact)
}

Ising_PseudoLikelihood_Cpp <- function(x, graph, thresholds, responses, logis) {
    .Call(`_CARlasso_Ising_PseudoLikelihood_Cpp`, x, graph, thresholds, responses, logis)
}

Multinomial_CAR_ALASSO_randeff_Cpp <- function(data, design, design_r, membership, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, alpha, beta, ns, m, emax, progress) {
    .Call(`_CARlasso_Multinomial_CAR_ALASSO_randeff_Cpp`, data, design, design_r, membership, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, alpha, beta, ns, m, emax, progress)
}

Multinomial_CAR_ALASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, lambda_diag, ns, m, emax, progress) {
    .Call(`_CARlasso_Multinomial_CAR_ALASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, lambda_diag, ns, m, emax, progress)
}

Multinomial_CAR_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, ns, m, emax, progress) {
    .Call(`_CARlasso_Multinomial_CAR_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, ns, m, emax, progress)
}

Pois_CAR_ALASSO_randeff_Cpp <- function(data, design, design_r, membership, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, alpha, beta, ns, m, emax, progress) {
    .Call(`_CARlasso_Pois_CAR_ALASSO_randeff_Cpp`, data, design, design_r, membership, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, alpha, beta, ns, m, emax, progress)
}

Pois_CAR_ALASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, lambda_diag, ns, m, emax, progress) {
    .Call(`_CARlasso_Pois_CAR_ALASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, lambda_diag, ns, m, emax, progress)
}

Pois_CAR_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, ns, m, emax, progress) {
    .Call(`_CARlasso_Pois_CAR_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, ns, m, emax, progress)
}

Pois_SRG_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, ns, m, emax, progress) {
    .Call(`_CARlasso_Pois_SRG_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, ns, m, emax, progress)
}

Probit_CAR_ALASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, lambda_diag, progress) {
    .Call(`_CARlasso_Probit_CAR_ALASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, lambda_diag, progress)
}

Probit_CAR_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress) {
    .Call(`_CARlasso_Probit_CAR_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress)
}

Probit_Graphical_LASSO_Cpp <- function(data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress) {
    .Call(`_CARlasso_Probit_Graphical_LASSO_Cpp`, data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress)
}

Probit_SRG_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress) {
    .Call(`_CARlasso_Probit_SRG_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress)
}

update_Z_helper_CAR <- function(Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n) {
    invisible(.Call(`_CARlasso_update_Z_helper_CAR`, Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n))
}

SRG_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress) {
    .Call(`_CARlasso_SRG_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress)
}

update_beta1_helper <- function(data, design, mu, tau2, Omega, k, p, n) {
    .Call(`_CARlasso_update_beta1_helper`, data, design, mu, tau2, Omega, k, p, n)
}

update_beta_helper <- function(data, design, mu, tau2, Omega, k, p, n) {
    .Call(`_CARlasso_update_beta_helper`, data, design, mu, tau2, Omega, k, p, n)
}

Sigma_to_CAR_Cpp <- function(Sigma) {
    .Call(`_CARlasso_Sigma_to_CAR_Cpp`, Sigma)
}

rtn1 <- function(mean, sd, low, high) {
    .Call(`_CARlasso_rtn1`, mean, sd, low, high)
}

ZIP_SRG_LASSO_Cpp <- function(data, design_P, design_ZI, n_iter, n_burn_in, thin_by, r_beta_P, delta_beta_P, r_Omega_P, delta_Omega_P, r_beta_ZI, delta_beta_ZI, r_Omega_ZI, delta_Omega_ZI, ns, m, emax, progress) {
    .Call(`_CARlasso_ZIP_SRG_LASSO_Cpp`, data, design_P, design_ZI, n_iter, n_burn_in, thin_by, r_beta_P, delta_beta_P, r_Omega_P, delta_Omega_P, r_beta_ZI, delta_beta_ZI, r_Omega_ZI, delta_Omega_ZI, ns, m, emax, progress)
}

update_Z_helper_multinomial <- function(Z_curr, mu_Z, Sigma_Z, y, k, p, n, ns, m, emax) {
    invisible(.Call(`_CARlasso_update_Z_helper_multinomial`, Z_curr, mu_Z, Sigma_Z, y, k, p, n, ns, m, emax))
}

update_Z_helper_multinomial_para <- function(Z_curr, mu_Z, Sigma_Z, y, k, p, n, ns, m, emax) {
    invisible(.Call(`_CARlasso_update_Z_helper_multinomial_para`, Z_curr, mu_Z, Sigma_Z, y, k, p, n, ns, m, emax))
}

update_Z_helper_multinomial_SRG <- function(Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n, ns, m, emax) {
    invisible(.Call(`_CARlasso_update_Z_helper_multinomial_SRG`, Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n, ns, m, emax))
}

update_Z_helper_multinomial_CAR <- function(Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n, ns, m, emax) {
    invisible(.Call(`_CARlasso_update_Z_helper_multinomial_CAR`, Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n, ns, m, emax))
}

update_Z_helper_multinomial_CAR_randeff <- function(Z_curr, data, design, design_r, mu_curr, beta_curr, nu_curr, Omega_curr, k, p, n, ns, m, emax) {
    invisible(.Call(`_CARlasso_update_Z_helper_multinomial_CAR_randeff`, Z_curr, data, design, design_r, mu_curr, beta_curr, nu_curr, Omega_curr, k, p, n, ns, m, emax))
}

update_Z_helper_Pois <- function(Z_curr, mu_Z, Sigma_Z, y, k, p, n, ns, m, emax) {
    invisible(.Call(`_CARlasso_update_Z_helper_Pois`, Z_curr, mu_Z, Sigma_Z, y, k, p, n, ns, m, emax))
}

update_Z_helper_Pois_reg <- function(Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n, ns, m, emax) {
    invisible(.Call(`_CARlasso_update_Z_helper_Pois_reg`, Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n, ns, m, emax))
}

update_Z_helper_Pois_CAR <- function(Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n, ns, m, emax) {
    invisible(.Call(`_CARlasso_update_Z_helper_Pois_CAR`, Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n, ns, m, emax))
}

update_Z_helper_Pois_CAR_randeff <- function(Z_curr, data, design, design_r, mu_curr, beta_curr, nu_curr, Omega_curr, k, p, n, ns, m, emax) {
    invisible(.Call(`_CARlasso_update_Z_helper_Pois_CAR_randeff`, Z_curr, data, design, design_r, mu_curr, beta_curr, nu_curr, Omega_curr, k, p, n, ns, m, emax))
}

update_Z_helper_Pois_para <- function(Z_curr, mu_Z, Sigma_Z, y, k, p, n, ns, m, emax) {
    invisible(.Call(`_CARlasso_update_Z_helper_Pois_para`, Z_curr, mu_Z, Sigma_Z, y, k, p, n, ns, m, emax))
}

Graphical_ALASSO_Cpp <- function(data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress) {
    .Call(`_CARlasso_Graphical_ALASSO_Cpp`, data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress)
}

Graphical_LASSO_Cpp <- function(data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress) {
    .Call(`_CARlasso_Graphical_LASSO_Cpp`, data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress)
}

Intercept_Graphical_ALASSO_Cpp <- function(data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress) {
    .Call(`_CARlasso_Intercept_Graphical_ALASSO_Cpp`, data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress)
}

Intercept_Graphical_LASSO_Cpp <- function(data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress) {
    .Call(`_CARlasso_Intercept_Graphical_LASSO_Cpp`, data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress)
}

rinvGau <- function(mu, lambda) {
    .Call(`_CARlasso_rinvGau`, mu, lambda)
}

stein_loss_cpp <- function(Omega, Omega_hat) {
    .Call(`_CARlasso_stein_loss_cpp`, Omega, Omega_hat)
}

rmultireg <- function(Y, X, Bbar, A, nu, V) {
    .Call(`_CARlasso_rmultireg`, Y, X, Bbar, A, nu, V)
}

gig_mode <- function(lambda, omega) {
    .Call(`_CARlasso_gig_mode`, lambda, omega)
}

rgig_ROU_noshift <- function(lambda, lambda_old, omega, alpha) {
    .Call(`_CARlasso_rgig_ROU_noshift`, lambda, lambda_old, omega, alpha)
}

