# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Auto_Poisson_Gibbs_Batch_Cpp <- function(Nsample, graph, thresholds, Winsorized, nIter) {
    .Call(`_SRGlasso_Auto_Poisson_Gibbs_Batch_Cpp`, Nsample, graph, thresholds, Winsorized, nIter)
}

Auto_Poisson_Pseudo_likelihood_Cpp <- function(Sample, graph, thresholds) {
    .Call(`_SRGlasso_Auto_Poisson_Pseudo_likelihood_Cpp`, Sample, graph, thresholds)
}

CAR_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress) {
    .Call(`_SRGlasso_CAR_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress)
}

update_car_beta_helper <- function(data, design, mu, tau2, Omega, k, p, n) {
    .Call(`_SRGlasso_update_car_beta_helper`, data, design, mu, tau2, Omega, k, p, n)
}

update_car_mu_helper <- function(data, design, beta, Omega, k, p, n) {
    .Call(`_SRGlasso_update_car_mu_helper`, data, design, beta, Omega, k, p, n)
}

update_car_Omega_helper <- function(Omega, data, design, mu, beta, lambda_curr, k, p, n) {
    invisible(.Call(`_SRGlasso_update_car_Omega_helper`, Omega, data, design, mu, beta, lambda_curr, k, p, n))
}

update_car_tau2_helper <- function(beta, lambda2, Omega, k, p, n) {
    .Call(`_SRGlasso_update_car_tau2_helper`, beta, lambda2, Omega, k, p, n)
}

rgig <- function(lambda, chi, psi) {
    .Call(`_SRGlasso_rgig`, lambda, chi, psi)
}

Ising_LASSO_Cpp <- function(data_, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_J, delta_J, propsd_mu, propsd_beta, propsd_J, propsd_lambda, exact, nauxIter, progress, verbos, reportby) {
    .Call(`_SRGlasso_Ising_LASSO_Cpp`, data_, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_J, delta_J, propsd_mu, propsd_beta, propsd_J, propsd_lambda, exact, nauxIter, progress, verbos, reportby)
}

IsingSamplerCpp <- function(n, graph, thresholds, nIter, responses, exact) {
    .Call(`_SRGlasso_IsingSamplerCpp`, n, graph, thresholds, nIter, responses, exact)
}

Ising_PseudoLikelihood_Cpp <- function(x, graph, thresholds, responses, logis) {
    .Call(`_SRGlasso_Ising_PseudoLikelihood_Cpp`, x, graph, thresholds, responses, logis)
}

Pois_SRG_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, ns, m, emax, progress) {
    .Call(`_SRGlasso_Pois_SRG_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, ns, m, emax, progress)
}

Proit_CAR_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress) {
    .Call(`_SRGlasso_Proit_CAR_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress)
}

Probit_Graphical_LASSO_Cpp <- function(data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress) {
    .Call(`_SRGlasso_Probit_Graphical_LASSO_Cpp`, data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress)
}

Proit_SRG_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress) {
    .Call(`_SRGlasso_Proit_SRG_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress)
}

SRG_LASSO_Cpp <- function(data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress) {
    .Call(`_SRGlasso_SRG_LASSO_Cpp`, data, design, n_iter, n_burn_in, thin_by, r_beta, delta_beta, r_Omega, delta_Omega, progress)
}

Sigma_to_CAR_Cpp <- function(Sigma) {
    .Call(`_SRGlasso_Sigma_to_CAR_Cpp`, Sigma)
}

rtn1 <- function(mean, sd, low, high) {
    .Call(`_SRGlasso_rtn1`, mean, sd, low, high)
}

ZIP_SRG_LASSO_Cpp <- function(data, design_P, design_ZI, n_iter, n_burn_in, thin_by, r_beta_P, delta_beta_P, r_Omega_P, delta_Omega_P, r_beta_ZI, delta_beta_ZI, r_Omega_ZI, delta_Omega_ZI, ns, m, emax, progress) {
    .Call(`_SRGlasso_ZIP_SRG_LASSO_Cpp`, data, design_P, design_ZI, n_iter, n_burn_in, thin_by, r_beta_P, delta_beta_P, r_Omega_P, delta_Omega_P, r_beta_ZI, delta_beta_ZI, r_Omega_ZI, delta_Omega_ZI, ns, m, emax, progress)
}

logPostZij_helper_Cpp <- function(i, j, Z_curr, mu_Z, Sigma_Z, y, k, p, n) {
    .Call(`_SRGlasso_logPostZij_helper_Cpp`, i, j, Z_curr, mu_Z, Sigma_Z, y, k, p, n)
}

update_Z_helper_Pois <- function(Z_curr, mu_Z, Sigma_Z, y, k, p, n, ns, m, emax) {
    invisible(.Call(`_SRGlasso_update_Z_helper_Pois`, Z_curr, mu_Z, Sigma_Z, y, k, p, n, ns, m, emax))
}

update_Z_helper_Pois_reg <- function(Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n, ns, m, emax) {
    invisible(.Call(`_SRGlasso_update_Z_helper_Pois_reg`, Z_curr, data, design, mu_curr, beta_curr, Omega_curr, k, p, n, ns, m, emax))
}

Graphical_LASSO_Cpp <- function(data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress) {
    .Call(`_SRGlasso_Graphical_LASSO_Cpp`, data, n_iter, n_burn_in, thin_by, lambda_a, lambda_b, progress)
}

rinvGau <- function(mu, lambda) {
    .Call(`_SRGlasso_rinvGau`, mu, lambda)
}

gig_mode <- function(lambda, omega) {
    .Call(`_SRGlasso_gig_mode`, lambda, omega)
}

rgig_ROU_noshift <- function(lambda, lambda_old, omega, alpha) {
    .Call(`_SRGlasso_rgig_ROU_noshift`, lambda, lambda_old, omega, alpha)
}

